Big refactor
PySymGym/PySymGym pull request #120
Opened 2024-10-18 14:40 UTC by Anya497

- Refactor statistics collector. Replace ASCII table with `csv` file for maps results
- Log single SVM average coverage and number of failed maps to mlflow
- Refactor `run_training.py`. Move validation function initialization to `run_training` function. `objective`  function responsible only for running `training-validation` cycle regardless of validation type
- Move `fail_immediately` flag and `PlatformsConfig` to `ValidationWithSVMs` because they are necessary only for this validation type

2024-10-18 15:21 UTC, gsvgit requested changes

2024-10-18 15:21 UTC, gsvgit commented on AIAgent/ml/training/validation.py
> +                    maps_to_remove.append(result.map2result.map)
`maps_to_remove` will be used to check whether should we fail immediately but here we use additional flag `need_to_save_map` to fill this collection. Looks strange.

2024-10-18 15:21 UTC, gsvgit commented on AIAgent/run_training.py
> +            if maps_to_remove and validation_config.validation.fail_immediately:
Look at [this code](https://github.com/PySymGym/PySymGym/pull/120/files#diff-3f4e39c863773963ee6442034b7b73bcac4f3003ea83f881cdafaf824ecf3be7R85). `fail_immediate`  must be independent from other flags. CI must fails on any problems with maps in any cases.

2024-10-18 15:21 UTC, gsvgit commented on AIAgent/run_training.py
> +                svms_info = platform.svms_info
Can be inlined.

2024-10-18 15:21 UTC, gsvgit commented on AIAgent/run_training.py
> +                        dataset_base_path = dataset_config.dataset_base_path
The body can be moved to top-level function, after that residual code can be inlined as list generator.

2024-10-19 13:19 UTC, Parzival-05 requested changes

2024-10-21 10:01 UTC, gsvgit commented on AIAgent/ml/training/validation.py
> +                    raise RuntimeError("Validation failed")
I think, we can return to this question back later an fix it separately.

2024-10-21 10:01 UTC, gsvgit commented on AIAgent/ml/training/utils.py
> +    return df
Well... But utils reorganization is a separated task.

2024-10-22 10:53 UTC, Anya497 commented on AIAgent/ml/training/validation.py
> +                    raise RuntimeError("Validation failed")
I've created the [issue](https://github.com/PySymGym/PySymGym/issues/130).

2024-10-22 10:58 UTC, Anya497 commented on AIAgent/ml/training/statistics.py
> +    return metrics["average_coverage"], metrics
We need separate metric which is used for tuning hyperparameters with `optuna`. I think it's better define it here.

2024-10-22 11:04 UTC, Anya497 commented on AIAgent/ml/training/utils.py
> +    return df
These functions can be useful for some special experiments or for analysis of the results. They are not the part of training pipeline and this is the reason of their location in `utils`.

2024-10-25 11:14 UTC, gsvgit commented on AIAgent/ml/training/statistics.py
> +            "actual_coverage_percent",
`"actual_coverage_percent"` used at least twice. Move it to (local) constant.

2024-10-25 11:26 UTC, gsvgit commented on AIAgent/ml/training/statistics.py
> +    return metrics["average_coverage"], metrics
Look at https://github.com/PySymGym/PySymGym/pull/120/files#diff-c197b7ad994b864760fb400630cf61a275cb411f3ae6eacd3fe8de399fa54e1eR131

2024-10-25 11:35 UTC, gsvgit commented on AIAgent/tests/test_statistics.py
> +        shutil.rmtree("tests/tmp")
Move to constant

2024-10-25 11:39 UTC, gsvgit commented on AIAgent/tests/test_statistics.py
> +            "average_coverage": 100.0,
Can we generate names using svms?
Can we move svm-independent names to constants to reuse  [here](https://github.com/PySymGym/PySymGym/pull/120/files#diff-77b01a395331db59634890091292862d8a6cdbaaf4de890c56bbc4c67d845667R49)

2024-10-27 10:57 UTC, Parzival-05 commented on AIAgent/common/classes.py
> +    game_result: Union[GameResult, GameFailed]
👍

2024-10-27 10:57 UTC, Parzival-05 commented on AIAgent/ml/game/play_game.py
> -        raise GameError(game_map2svm=game_map2svm, error_name=error.__class__.__name__)
Copypasta

2024-10-27 10:57 UTC, Parzival-05 commented on AIAgent/tests/resources/svms_validation_configs/real_svms_config.yml
> +          server_working_dir: ../GameServers/usvm/usvm-ml-gameserver/build/libs/
\n

2024-10-28 07:43 UTC, Anya497 commented on AIAgent/ml/game/play_game.py
> -        raise GameError(game_map2svm=game_map2svm, error_name=error.__class__.__name__)
I didn't understand you

2024-10-28 11:55 UTC, gsvgit commented on AIAgent/ml/training/statistics.py
> +    GAME_RESULT_COVERAGE_PERCENT_ATTR = "actual_coverage_percent"
Can it be moved up, to collect all literals in one single place?

2024-10-28 11:55 UTC, gsvgit commented on AIAgent/ml/training/statistics.py
> +            dataset.maps_results.values(), "coverage_percent"
Can `"coverage_percent"` be declared as constant literal? Just for unification.

2024-10-29 17:41 UTC, gsvgit approved these changes

2024-10-29 17:54 UTC, Parzival-05 approved these changes

2024-10-30 04:20 UTC, merged