New validation design
PySymGym/PySymGym pull request #194
Opened 2024-12-12 05:00 UTC by Parzival-05

2024-12-12 06:47 UTC, emnigma commented
can you describe the reason for this change?

2024-12-13 09:11 UTC, emnigma requested changes

2024-12-13 09:11 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/base_game_manager.py
> +        """`get_game_status` guarantees to receive the steps of the played game no more than once
1. I see, below you have a collection from which you are popping the element. I think, this implementation detail (once popped, game state no longer exists on collection) as it is now can be a child's responsibility. Or if this constraint should be forced on base class level, then constrained behaviour should be implemented in base class itself

2024-12-24 04:57 UTC, Parzival-05 commented
@emnigma, thanks for the review, corrections made. Ready for re-review.

2024-12-24 23:20 UTC, Parzival-05 commented
@emnigma CI is fixed

2025-02-06 14:54 UTC, emnigma approved these changes
👍

2025-02-06 15:23 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/game_managers/each_step/each_step_game_manager.py
> +        self._game_states[str(game_map2svm.GameMap)] = map_steps
Why not?

2025-02-06 15:23 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +        result: Map2Result | Exception = catching_play_game_map(game_map2svm)
Yes, error logging is essential, thank you

2025-02-06 15:47 UTC, Anya497 commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +        result: Map2Result | Exception = catching_play_game_map(game_map2svm)
I think in this case it's better to fall with this exception because mistakes in Python code is need and able be fixed before validation running.

2025-02-11 06:56 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/game_managers/each_step/each_step_game_manager.py
> +        self._game_states[str(game_map2svm.GameMap)] = map_steps
1. What does "bulky" mean?
2. Uniqueness of the name must be documented

2025-02-11 07:06 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +        result: Map2Result | Exception = catching_play_game_map(game_map2svm)
Propagating exceptions through the process pool isn't straightforward and requires further consideration. I'll open an issue regarding this. For now, I suggest a workaround. If there's any error in the logic, the validation will terminate quickly, and the user will be able to understand the issue from the logs.

2025-02-19 06:21 UTC, Anya497 commented on AIAgent/ml/validation/coverage/game_managers/each_step/each_step_game_manager.py
> +        self._game_states[str(game_map2svm.GameMap)] = map_steps
1. It's not so important. Just seemed a little unusual to me.  
2. You're right. I created the [issue](https://github.com/PySymGym/PySymGym/issues/231) about it.

2025-02-21 08:27 UTC, Anya497 approved these changes

2025-02-21 08:28 UTC, gsvgit approved these changes

2025-02-21 08:28 UTC, merged