New validation mode: via sending model
PySymGym/PySymGym pull request #205
Opened 2024-12-27 04:48 UTC by Parzival-05

2025-02-06 15:16 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        launch_command = f"""python onyx.py --sample-gamestate {GAMESTATE_EXAMPLE_PATH}
you can call it directly, import `entrypoint` as something

https://github.com/PySymGym/PySymGym/blob/5b7a6ebbd8644af9d0b18ba12b8d5da56f6f2866/AIAgent/onyx.py#L201

2025-02-06 15:16 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +            cwd=Path(svm_info.server_working_dir),
`Path(svm_info.server_working_dir).resolve`? If user provides relative path, this can fail to find the correct wdir

2025-02-06 15:16 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +                readed_game_state = get_game_state()
```suggestion
                received_game_state = get_game_state()
```

2025-02-06 15:16 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +            nn_output = list(map(lambda x: [x], nn_output[0]))
```suggestion
            nn_output = [[x], for x in nn_output[0]]
```

2025-02-06 15:16 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        else:
```suggestion
            result = GameResult(game_map2svm.GameMap.StepsToPlay, 0, 0, 0)
            return result
```

and dedent code in current else branch

2025-02-11 07:34 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        else:
What's wrong and what do you suggest?

2025-02-12 13:44 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        else:
instead of:
```py
if a:
    a = branchA()
    return a
else:
    b = branchB()
    return b
```

do:
```py
if a:
    a = branchA()
    return a
b = branchB()
return b
```

2025-03-04 06:50 UTC, Anya497 commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        svm_info = game_map2svm.SVMInfo
`svm_info` is assigned in both lines.

2025-03-06 15:09 UTC, emnigma requested changes

2025-03-06 15:09 UTC, emnigma commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +                self._game_manager.are_steps_required(game_map=game_map, required=True)
should be split into 2 funcs? `run_<something>_with_update` and `run_<something>`? or maybe provide a callback with `game_map` argument? idk. this function clearly does 2 things, should do 1

2025-03-09 10:02 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +                self._game_manager.are_steps_required(game_map=game_map, required=True)
I rewrote it a bit, is it ok now? Or please specify what you are suggesting

2025-03-13 06:22 UTC, gsvgit requested changes

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +            proc=None,  # type: ignore
Too much problems with types -> design is wrong.

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        logging.debug(f"Looking for port... Attempls left: {attempts}.")
Why this logic is not in connection manager (utils?)?

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +                steps = list(map(lambda v: ModelGameStep.from_dict(v), steps_json))  # type: ignore
Such tricks with types hint at bad design.

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +            def convert_steps_to_hetero(steps: list):
List of what?

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +                def get_hetero_data(game_state: GameState, nn_output: list):
May be moved to dataset?

2025-03-13 06:22 UTC, gsvgit commented on AIAgent/run_training.py
> +            model_kwargs = trial.params.copy()
What is it?

2025-03-15 21:36 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +        logging.debug(f"Looking for port... Attempls left: {attempts}.")
Done

2025-03-17 13:22 UTC, emnigma reviewed
A lot of TODOs still. Will they be fixed? Or you want to merge them?

2025-03-17 13:22 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +                steps = list(map(lambda v: ModelGameStep.from_dict(v), steps_json))  # type: ignore
Try this: https://github.com/lidatong/dataclasses-json?tab=readme-ov-file#use-my-dataclass-with-json-arrays-or-objects

<img width="752" alt="image" src="https://github.com/user-attachments/assets/1bd1ca1d-89e1-4482-98e2-fddb17e46ef9" />

2025-03-17 13:22 UTC, emnigma commented on AIAgent/ml/validation/coverage/game_managers/model/process_game_manager.py
> +    def are_steps_required(self, game_map: GameMap, required: bool):
what is "pollute the class namespace"? If the issue is in duck typing hints, you can create static class and put these functions inside

I am suggesting this change because rn this function is unreadable to the reviewer. Also imagine you need to test `convert_steps_to_hetero` function. How would you do it?

2025-03-17 13:22 UTC, emnigma commented on AIAgent/ml/validation/coverage/validate_coverage.py
> +                self._game_manager.are_steps_required(game_map=game_map, required=True)
why something is run after `alert_svm_about_step_saving`? According to this func documentation, "symbolic execution environment" is "notified", why something else is happening?

2025-04-03 16:13 UTC, Parzival-05 commented
> A lot of TODOs still. Will they be fixed? Or you want to merge them?

It's not critical yet, I'll come back later

2025-04-08 08:15 UTC, Anya497 commented on AIAgent/ml/validation/coverage/game_managers/model/game_utils.py
> +        steps_hetero.append(hetero_input)
Why does it necessary to process the first  step separately?

2025-04-17 11:48 UTC, emnigma approved these changes

2025-04-17 19:11 UTC, Parzival-05 commented on AIAgent/ml/validation/coverage/game_managers/model/game_utils.py
> +        steps_hetero.append(hetero_input)
Steps are updated incrementally, so the first step is interpreted as a step, not the delta between the steps

2025-04-17 19:37 UTC, Anya497 commented on AIAgent/ml/validation/coverage/game_managers/model/game_utils.py
> +        steps_hetero.append(hetero_input)
Understood, thanks!

2025-04-17 19:39 UTC, Anya497 approved these changes

2025-08-22 07:05 UTC, merged